{
 "title": "real_estate_model_prediction",
 "description": "Метрики модели предсказания цены недвижимости.",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Цена (медиана)",
   "type": "timeseries",
   "description": "Медианное значение предсказываемой цены на недвижимость ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Цена (квантили)",
   "type": "timeseries",
   "description": "Квантили 0,05 и 0,95 предсказываемой цены на недвижимость",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Трафик",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя скорость прогноза",
   "type": "gauge",
   "description": "Средняя длительность получения предсказания",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_time_seconds_sum / prediction_time_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}