services:
  main-app:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile_ml_service
    ports:
      - "${APP_VM_PORT}:${APP_DOCKER_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /real_estate_app/models